### ISSUE TITLE
Proposed methodology

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/DSCI522_Team_23#16]
- You mentioned that you will check for collinearity between variables. I suggest you clarify how you are going to deal with cases of collinearity. Are you going to do factor analysis, dimensionality reduction, or use other classification algorithms that deal with collinearity?

- Because you are proposing a predictive research question. You should mention how are you going to split the data into training and testing data sets.

**Comment by jiajie0225** [comment]
Hi @hsmohammed, for splitting the data, we have combined the red wine and white wine data to become one dataset. From there, we then perform a train-test split. Do you want me to add this to the proposal?

Also for checking the collinearity between variables, we were thinking of using feature correlations, not sure about other methods since we have not learned much. Could you provide us with some suggestions?

**Comment by jiajie0225** [comment]
Hi @hsmohammed, we have proposed two methods including SVMs and KNN in our methods. For KNN, we are planning to do a forward or backward search, which we have just learned from DSCI 573. Also, for SVM, since collinearity is not a problem, we can keep it as it. 

Reference: 
https://stats.stackexchange.com/questions/35708/how-to-avoid-multicolinearity-in-svm-input-data
