### ISSUE TITLE
Exploratory data analysis

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/DSCI522_Team_23#17]
- You will be using 11 variables in your prediction (classification) model. Why are you showing the bar charts for only 5 of these?

- Also, consider plotting the distributions of explanatory variables instead of bar charts.

- What are you proposing to do with the class imbalance problem?

**Comment by wangjc640** [comment]
Thanks for the feedback. I tried to plot the distribution using scatter plots. But the class we're dealing with is about 9, thus the scatter plot is quite messy. I've added all 11 variables plots, for now, we just using bar charts. But we're discussing the solution of splitting 9 classes into 3 classes. So that scatter plot can make more sense. 

After we split classes into 3, the imbalance problem still exists. and we will use class_weight = 'balanced' in the model to solve this issue.

**Comment by ZIBOWANGKANGYU** [comment]
Hi Jiacheng I have modified the `EDA.py` file a little bit so that it can generate all 11 figures automatically using the command line. However, I think the 11 figures are very similar to each other in terms of formatting and maybe we can use `AltAir`'s [repeated chart](https://altair-viz.github.io/user_guide/compound_charts.html) functionality to make them a single big chart. Maybe we can do this next week.

**Comment by wangjc640** [comment]
Will do!
